name: Build docs

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install -r docs/requirements.txt
    - name: Build docs
      run: |
        cd docs
        make html
