# Publishes release to PyPI once it's published in GitHub
name: Publish to PyPI

on:
  release:
    types:
      - published

jobs:
  publish_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
       python -m pip install -U pip
       pip install -r requirements.txt
    - name: Build packages
      run: python setup.py sdist bdist_wheel
    - name: Upload packages
      run: twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
